// This file is automatically generated. Do not edit it manually.
// This file contains all the locators used in the tests.
// This file is used to import all the locators from the other files.
import kioskElement from "./kiosk_element";


const elements = {
  kiosk: kioskElement,
  

};

export default elements;
